---
title: "local_imp_functions"
author: "Kelvyn Bladen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(fastDummies)
library(caret)
library(rpart)
library(tidyverse)
library(GGally)
library(treeshap)
library(lime)
library(patchwork)
library(tictoc)
```

```{r, eval=FALSE, echo=FALSE}
# rm(list = ls())   # remove all objects
# gc()              # force garbage collection

unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(randomForest)
library(tidyverse)
library(patchwork)
library(randomForestVIP)
library(caret)
library(scales)
library(ggeasy)

train_models1 <- function(x, y, folds, flds0, method, tuneGrid) { # caret
  models <- vector("list", length(folds))
  for (k in seq_len(folds)) {
    models[[k]] <- caret::train(
      x[flds0 != k, ], y[flds0 != k],
      method = method,
      tuneGrid = tuneGrid,
      trControl = caret::trainControl(method = "none",
        classProbs = TRUE)
    )
  }
  return(models)
}

# Helper function to generate grid values
generate_grid_values1 <- function(xi, y, nsim, quantile_grid) {
  if (!is.numeric(xi)) {
    grid_v <- round(nsim * table(y) / length(y))
    gd <- min(pracma::gcd(grid_v[1], grid_v))
    grid_vals <- (grid_v / gd) |> as.data.frame() |> uncount(Freq) |> pull(1)
  } else {
    grid_vals <- if (quantile_grid) {
      quantile(xi, probs = seq(0, 1, length = nsim)) # Quantile-based grid
    } else {
      seq(min(xi), max(xi), length = nsim) # Uniform grid
    }
  }
  grid_vals
}

# Update predictions and calculate errors
calculate_new_m1 <- function(grid_val, x, ii, mods, flds0, truth, typ,
                            predictions) {
  x_new <- x
  #x_new[, ii] <- grid_val
  x_new[, ii] <- x[sample(1:nrow(x)), ii]
  

  for (k in seq_along(mods)) {
    if(brier_score){
      predictions[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,],
                                         type = typ)
    } else {
      predictions[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,],
                                        type = typ)
    }
  }
  predictions
  if(!is.factor(y)){
    return(abs(truth - predictions))
  } else if (brier_score){
    # Calculate the row-wise mean squared error
    return(rowMeans(abs(truth - predictions)))
  } else {
    return(as.numeric(truth != predictions))
  }
}

get_var_loc1 <- function(ii, x, y, truth, nsim, mods, flds0, m, typ,
                  quantile_grid, predictions) { # depends on y

  # Generate grid values for the selected variable
  grid_vals <- generate_grid_values1(x[, ii], y, nsim, quantile_grid)

  # Apply over all grid values
  new_m_mat <- sapply(grid_vals, calculate_new_m1, x = x, ii = ii,
                      mods = mods, flds0 = flds0, truth = truth, typ = typ,
                      predictions = predictions)

  # Calculate the mean error for each observation and adjust by baseline errors
  rowMeans(new_m_mat) - m
}


# Main function
local_perm_imp_cm <- function(formula = medv ~ ., data = Boston,
                   method = "rf", tuneGrid = tuneGrid,
                   parallel = F, cores = 5, seed = 123,
                   nsim = 25, folds = 5, quantile_grid = TRUE,
                   brier_score = FALSE) {
  # Set up the data
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  if (is.factor(y)) {
    y <- factor(y, labels = make.names(levels(y)))
  }

  # Set up cross-validation folds
  set.seed(seed)
  flds <- caret::createFolds(y, k = folds, returnTrain = TRUE)
  set.seed(seed)
  flds0 <- caret::createFolds(y, k = folds, list = FALSE, returnTrain = FALSE)

  # Train the global model
  global_model <- caret::train(
    x, y,
    method = method,
    tuneGrid = tuneGrid,
    trControl = trainControl(
      method = "cv",
      index = flds,
      savePredictions = "final",
      classProbs = TRUE
    )
  )

  # Parallel setup
  if (parallel) {
    cl <- parallel::makeCluster(cores)
    doParallel::registerDoParallel(cl)
    on.exit({
      parallel::stopCluster(cl)
      env <- foreach:::.foreachGlobals
      rm(list=ls(name=env), pos=env)
    })
  }

  # Train models for each fold
  mods <- train_models1(x, y, folds, flds0, method,
                       global_model$finalModel$tuneValue)

  global_model$pred = global_model$pred %>% dplyr::arrange(rowIndex)

  # Calculate errors
  if (!is.factor(y)) {
    truth <- global_model$pred$obs
    predictions <- global_model$pred$pred
    m <- abs(truth - predictions)
  } else if (brier_score) {
    truth <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    predictions <- global_model$pred %>% dplyr::select(levels(y))
    m <- rowMeans(abs(truth - predictions))
  } else {
    truth <- global_model$pred$obs
    predictions <- global_model$pred$pred
    m <- as.numeric(truth != predictions)
  }

  # Task function for parallel computation
  x_loc <- future.apply::future_lapply(
    seq_len(nc),
    function(ii) {
      get_var_loc1(ii, x = x, y = y, truth = truth, nsim = nsim, mods = mods,
            flds0 = flds0, m = m, typ = ifelse(brier_score, "prob", "raw"),
            quantile_grid = quantile_grid, predictions = predictions)
    },
    future.seed = T
  ) %>% as.data.frame()
  colnames(x_loc) <- colnames(x)

  # Output
  list(
    bestTune = global_model$bestTune,
    results = global_model$results,
    finalModel = global_model$finalModel,
    local_imp = x_loc
  )
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
source("../../R/clique.R")
```

\newpage
# Sim

```{r, warning=FALSE, message=FALSE}
n <- 400 # increase higher 1000
set.seed(444) # 123
v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)
df <- data.frame(v1, v2, v3, y)

z1 = factor(df$v1 > -1/3)
z2 = factor(df$v2 > -1/3)
sup = factor(ifelse(z2 == F, "C", ifelse(z1 == F, "A", "B")))

gy = ggplot(df, aes(v1, v2, colour = y)) + geom_point() +
  scale_color_manual(values = c("#2CA02C", "#9467BD"))
gr = ggplot(df, aes(v1, v2, colour = sup)) + geom_point() +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))

tuneGrid <- expand.grid(mtry = 2)
k = 1
mm <- vector("list", length = 50 * 5)

for(s in 1:50){
  for(i in c(2, 5, 10, 15, 20)){
    xl = local_perm_imp_cm(formula = y ~ ., data = df, seed = s,
                         method = "rf", tuneGrid = tuneGrid,
                         nsim = 25, folds = i, brier_score = T,
                         parallel = F)
  
    xg = clique(formula = y ~ ., data = df, parallel = F, cores = 5, 
                seed = s, method = "rf", tuneGrid = NULL, 
                nsim = 25, folds = i, quantile_grid = TRUE, brier_score = T)
    
    l = data.frame(perm = xl$local_imp$v1, 
                   grid = xg$local_imp$v1)
    l$group = sup
    
    l$m = i
    l$seed = s
    mm[[k]] = l
    print(k)
    k = k + 1
  }
}


df_all <- bind_rows(mm)

df_sum <- df_all %>%
  group_by(m, seed, group) %>%
  summarise(
    perm = mean(perm),
    grid = mean(grid),
    .groups = "drop"
  ) %>%
  group_by(m, group) %>%
  summarise(
    perm_mean = mean(perm),
    perm_sd   = sd(perm) / sqrt(n()),
    perm_min = min(perm),
    perm_max = max(perm),
    grid_mean = mean(grid),
    grid_sd   = sd(grid) / sqrt(n()),
    grid_min = min(grid),
    grid_max = max(grid),
    .groups = "drop"
  )

# df_sum <- df_all %>%
#   group_by(m, group) %>%
#   summarise(
#     perm_mean = mean(perm),
#     perm_sd   = sd(perm),
#     grid_mean = mean(grid),
#     grid_sd   = sd(grid),
#     .groups = "drop"
#   )

library(tidyr)

df_plot <- df_sum %>%
  pivot_longer(
    cols = c(perm_mean, grid_mean, perm_sd, grid_sd, perm_min, grid_min,
             perm_max, grid_max),
    names_to = c("method", ".value"),
    names_pattern = "(perm|grid)_(mean|sd|min|max)"
  )

df_plot$method = ifelse(df_plot$method == "perm", "Permute", "Quantile")

library(ggplot2)

df_plot$method = factor(df_plot$method)

ggplot(df_plot, aes(x = m, 
                    y = mean, 
                    color = method,
                    group = method)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = min, ymax = max),
                width = 1.5, linewidth = 0.8) +
  ggh4x::facet_grid2(group ~ method, scales = "free_y") +
  ggh4x::facetted_pos_scales(
    y = list(group == "A" ~ scale_y_continuous(limits = c(0.602, 0.658),
                                       breaks = seq(0.61, 0.65, 0.02)),
      group == "B" ~ scale_y_continuous(limits = c(0.322, 0.378),
                                       breaks = seq(0.33, 0.37, 0.02)),
      group == "C" ~ scale_y_continuous(limits = c(-0.028, 0.028),
                                       breaks = seq(-0.02, 0.02, 0.02))
    )
  ) +
  scale_x_continuous(limits = c(1,21), breaks = c(1, 1:4*5)) +
  scale_color_manual(values = c("Quantile" = "#D95F02",
                                "Permute" = "#1B9E77"),
                     labels = c("Permute", "Quantile")) +
  labs(
    x = "Number of CV Folds",
    y = "Importance (mean ± extrema)",
    color = "Method"
  ) +
  theme_bw(base_size = 14)

ggsave("inst/plots/AND_kfolds_NEW1.pdf", dpi = 1200, height = 3.6, width = 7.2)

#####################

mmm = rbind(mm[[1]], mm[[2]], mm[[3]], mm[[4]], mm[[5]])

gg = ggplot(mmm, aes(x = m, y = grid, col = group)) + 
  geom_point(position = position_jitter(width = 0.1)) +
  ylab("v1 CLIQUE") +
  xlab("Folds") +
  geom_hline(yintercept = c(0)) + 
  scale_x_continuous(limits = c(0, 26), breaks = 0:5*5) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5) +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))
gg

gp = ggplot(mmm, aes(x = m, y = perm, col = group)) + 
  geom_point(position = position_jitter(width = 0.1)) +
  ylab("v1 CLIQUE") +
  xlab("Folds") +
  geom_hline(yintercept = c(0)) + 
  scale_x_continuous(limits = c(0, 26), breaks = 0:5*5) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5) +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))
gp


gdat + gp + gg + plot_layout(guides = "collect", axes = "collect",
                             widths = c(1,1,1))

ggsave("inst/plots/M_effect_reg.pdf", dpi = 1200, height = 2.4, width = 7.2)
```
