---
title: "local_imp_functions"
author: "Kelvyn Bladen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(fastDummies)
library(caret)
library(rpart)
library(tidyverse)
library(GGally)
library(treeshap)
library(lime)
tuneGrid <- expand.grid(mtry = 2)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
tuneGrid = NULL
local_grid_imp_cm <- function(formula = medv ~ ., data = Boston, 
                              method = "rf", tuneGrid = tuneGrid, 
                              nsim = 25, folds = 5, quantile_grid = TRUE) {
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  
  if (is(y, "factor")) {
    y = factor(y, labels = make.names(levels(y)))
  }
  
  set.seed(123)
  flds <- createFolds(y, k = folds, returnTrain = T)
  set.seed(123)
  flds0 <- createFolds(y, k = folds, list = F, returnTrain = F)
  
  model <- caret::train(x, y, 
                 # formula, data = data,
                 method = method,
                 tuneGrid = tuneGrid,
                 trControl = trainControl(method = "cv",
                                          index = flds,
                                          savePredictions = "final",
                                          classProbs = T))
   
  mods = list()
  for(k in 1:folds){
    mods[[k]] <- caret::train(x[flds0 != k,], y[flds0 != k], 
                 # formula, data = data,
                 method = method,
                 tuneGrid = model$finalModel$tuneValue,
                 trControl = trainControl(classProbs = T))
  }
  
  
  output = list()
  output$bestTune = model$bestTune
  output$results = model$results
  output$finalModel = model$finalModel

  model$pred = model$pred %>% arrange(rowIndex)

  x_loc <- x
  x_loc[, ] <- 0

  if (!is(y, "factor")) {
    p = model$pred$pred
    truth = model$pred$obs
    m <- abs(p - truth)
  } else {
    yd <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    p = model$pred %>% dplyr::select(levels(y))
    m <- rowMeans(abs(yd - p))
  }
  
  for (i in seq_len(nc)) {
    if(!inherits(x[,i], "numeric")){
      # perhaps do a permutation for low level factors!!
      # maybe convert factors to characters!!
      grid_vals = unique(x[,i])
    } else {
      grid_vals = ifelse(rep(quantile_grid, nsim),
      quantile(x[,i], probs = seq(0, 1, length = nsim)), #quantile
      seq(min(x[,i]), max(x[,i]), length = nsim)) #uniform
    }
    
    for (j in grid_vals) {
      x_new <- x
      x_new[, i] <- j

      if (!is(y, "factor")) {
        pr <- truth
        for(k in 1:folds){
          pr[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,], type = "raw")
        }
        new_m <- abs(pr - truth)
      } else {
        pr <- yd
        for(k in 1:folds){
          pr[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,], 
                                    type = "prob")
        }
        new_m <- rowMeans(abs(yd - pr))
      }
      x_loc[, i] <- x_loc[, i] + ((new_m - m) / nsim)
    }
  }
  output$local_imp = x_loc
  return(output)
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
source("R/clique.R")
```


\newpage

# Data

```{r, message=FALSE, warning=FALSE}
n <- 400 # increase higher 1000

set.seed(1234)

v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)
v4 = runif(n, -1, 1)

y = ifelse(v3 > 0, v1 + rnorm(n, sd = 0.01), v2 + rnorm(n, sd = 0.01))

df <- data.frame(v1, v2, v3, v4, y)

ggpairs(df)
ggpairs(df, mapping = aes(color = v3 > 0))
gdat = ggplot(df, aes(v1, y, colour = v3 > 0)) + geom_point(size = 2)
gdat
# ggsave("regint_data.pdf", dpi = 1600, width = 4, height = 2.5)
```

\newpage
# CV Training

```{r, warning=FALSE, message=FALSE}

tictoc::tic()
xae = clique(formula = y ~ ., data = df, parallel = T, cores = 5, seed = 123,
            method = "rf", tuneGrid = NULL, nsim = 25, folds = 5, 
            quantile_grid = TRUE, 
            loss_function = function(y, p)abs(y-p))
tictoc::toc()

tictoc::tic()
xse = clique(formula = y ~ ., data = df, parallel = T, cores = 5, seed = 123,
            method = "rf", tuneGrid = NULL, nsim = 25, folds = 5, 
            quantile_grid = TRUE,
            loss_function = function(y, p)(y-p)^2)
tictoc::toc()


d1 = data.frame(v1 = df[,1],
                ae = xae$local_imp$v1,
                se = xse$local_imp$v1,
                reg = v3 > 0)
ggpairs(d1)
ggpairs(d1, mapping = aes(color = v3 > 0))

d2 = d1 |> pivot_longer(cols = 2:3)

loss <- c(
  ae = "Absolute Error",
  se = "Squared Error"
)

gg = ggplot(d2, aes(x = v1, y = value, color = reg)) +
  geom_point() + 
  facet_grid(~name, labeller = labeller(
  name = loss)) +
  labs(y = "CLIQUE Importance",
       color = "v3 > 0")
gg

ggsave("inst/plots/regint_patch_1col.pdf", 
       dpi = 1600, width = 5.5, height = 3.3)

library(patchwork)

gdat + plot_spacer() + gg + ggeasy::easy_remove_legend() +
  plot_layout(guides = "collect", widths = c(6,0.2,12))

ggsave("inst/plots/regint_loss.pdf", 
       dpi = 1600, width = 8.4, height = 2.8)
8.8 / 3.3
```

