---
title: "local_imp_functions"
author: "Kelvyn Bladen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(fastDummies)
library(caret)
library(rpart)
library(tidyverse)
library(GGally)
library(treeshap)
library(lime)
library(doParallel)

unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
tuneGrid <- expand.grid(mtry = 2)
global_perm_imp_cm <- function(formula = Species ~ ., data = iris, 
                              method = "ranger", tuneGrid = tuneGrid, 
                              nsim = 25, folds = 5, seed = 42) {
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  nr <- nrow(x)
  
  if (is(y, "factor")) {
    y = factor(y, labels = make.names(levels(y)))
  }
  
  set.seed(seed + 20)
  flds <- createFolds(y, k = folds, returnTrain = T)
  set.seed(seed + 20)
  flds0 <- createFolds(y, k = folds, list = F, returnTrain = F)
  
  set.seed(seed)
  model <- train(x, y, 
                 # formula, data = data,
                 method = method,
                 tuneGrid = tuneGrid,
                 trControl = trainControl(method = "cv",
                                          index = flds,
                                          savePredictions = "final",
                                          classProbs = T))
  
  mods = list()
  for(i in 1:folds){
    mods[[i]] <- train(x[flds0 != i,], y[flds0 != i], 
                 # formula, data = data,
                 method = method,
                 tuneGrid = model$finalModel$tuneValue,
                 trControl = trainControl(classProbs = T))
  }
  
  
  output = list()
  output$bestTune = model$bestTune
  output$results = model$results
  output$finalModel = model$finalModel

  model$pred = model$pred %>% arrange(rowIndex)

  x_loc <- mat.or.vec(nsim, nc)
  x_temp <- x_loc

  if (!is(y, "factor")) {
    p = model$pred$pred
    truth = model$pred$obs
    m <- mean((p - truth)^2)
  } else {
    yd <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    p = model$pred %>% dplyr::select(levels(y))
    m <- mean(rowMeans((yd - p)^2))
  }

  for (j in seq_len(nsim)) {
    for (i in seq_len(nc)) {
      x_new <- x
      x_new[, i] <- x[sample(1:nr), i]

      if (!is(y, "factor")) {
        pr <- truth
        for(k in 1:folds){
          pr[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,], type = "raw")
        }
        new_m <- mean((pr - truth)^2)
      } else {
        pr <- yd
        for(k in 1:folds){
          pr[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,], 
                                    type = "prob")
        }
        new_m <- mean(rowMeans((yd - pr)^2))
      }
      x_temp[j,i] <- new_m - m
    }
    x_loc <- x_temp # x_loc + x_temp / nsim
  }
  output$global_imp = x_loc
  return(output)
}
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
tuneGrid <- expand.grid(mtry = 2)
global_grid_imp_cm <- function(formula = medv ~ ., data = Boston, 
                              method = "rf", tuneGrid = tuneGrid, 
                              nsim = 25, folds = 5, quantile_grid = TRUE, 
                              seed = 42) {
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  
  if (is(y, "factor")) {
    y = factor(y, labels = make.names(levels(y)))
  }
  
  set.seed(seed + 20)
  flds <- createFolds(y, k = folds, returnTrain = T)
  set.seed(seed + 20)
  flds0 <- createFolds(y, k = folds, list = F, returnTrain = F)
  
  set.seed(seed)
  model <- train(x, y, 
                 # formula, data = data,
                 method = method,
                 tuneGrid = tuneGrid,
                 trControl = trainControl(method = "cv",
                                          index = flds,
                                          savePredictions = "final",
                                          classProbs = T))
  
  mods = list()
  for(k in 1:folds){
    mods[[k]] <- train(x[flds0 != k,], y[flds0 != k], 
                 # formula, data = data,
                 method = method,
                 tuneGrid = model$finalModel$tuneValue,
                 trControl = trainControl(classProbs = T))
  }
  
  
  output = list()
  output$bestTune = model$bestTune
  output$results = model$results
  output$finalModel = model$finalModel

  model$pred = model$pred %>% arrange(rowIndex)

  x_loc <-  mat.or.vec(nsim, nc)

  if (!is(y, "factor")) {
    p = model$pred$pred
    truth = model$pred$obs
    m <- mean((p - truth)^2)
  } else {
    yd <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    p = model$pred %>% dplyr::select(levels(y))
    m <- mean(rowMeans((yd - p)^2))
  }
  
  for (i in seq_len(nc)) {
    if(!inherits(x[,i], "numeric")){
      # perhaps do a permutation for low level factors!!
      # maybe convert factors to characters!!
      grid_vals = unique(x[,i])
    } else {
      grid_vals = ifelse(rep(quantile_grid, nsim),
      quantile(x[,i], probs = seq(0, 1, length = nsim)), #quantile
      seq(min(x[,i]), max(x[,i]), length = nsim)) #uniform
    }
    
    for (j in seq_len(nsim)) {
      x_new <- x
      x_new[, i] <- grid_vals[j]

      if (!is(y, "factor")) {
        pr <- truth
        for(k in 1:folds){
          pr[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,], type = "raw")
        }
        new_m <- mean((pr - truth)^2)
      } else {
        pr <- yd
        for(k in 1:folds){
          pr[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,], 
                                    type = "prob")
        }
        new_m <- mean(rowMeans((yd - pr)^2))
      }
      x_loc[j,i] <- new_m - m
    }
  }
  output$global_imp = x_loc
  return(output)
}
```

\newpage
# Data

```{r, message=FALSE, warning=FALSE}
n <- 500 # increase higher 1000
d = 8
set.seed(123)
sig = diag(d)
df = MASS::mvrnorm(n = n, mu = rep(0, 8), Sigma = sig)
y = df %*% 7:0

dfc <- data.frame(df, y)

set.seed(12345)

v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)
v4 = runif(n, -1, 1)

y = ifelse(v1 + rnorm(n, sd = 0.00) < -1/4, 0, 
           ifelse(abs(v2) + rnorm(n, sd = 0.00) > 1/4, 1, 0))
y = as.factor(y)

dfc <- data.frame(v1, v2, v3, v4, y)

table(y)
ggplot(dfc, aes(v1, v2, colour = y)) + geom_point(size = 2)
```

```{r, message=FALSE, warning=FALSE}
nreps = 10
per = mat.or.vec(nreps, 4)
gri = mat.or.vec(nreps, 4) 
pl = vector("list", nreps)
gl = vector("list", nreps)

cl <- makePSOCKcluster(5)
registerDoParallel(cl)
for(q in 1:nreps){
  pg = global_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, 
                       nsim = 16, folds = 5, seed = q)
  xg = global_grid_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, 
                       nsim = 16, folds = 5, quantile_grid = TRUE)
  
  indp = (((pg$global_imp > 0)-.5)*2)
  indg = (((xg$global_imp > 0)-.5)*2)
  
  pl[[q]] = indp*sqrt(indp*pg$global_imp)
  gl[[q]] = indg*sqrt(indg*xg$global_imp)
  per[q,] = colMeans(indp*sqrt(indp*pg$global_imp))
  gri[q,] = colMeans(indg*sqrt(indg*xg$global_imp))
  #colMeans(sqrt(pmax(pg$global_imp, 0)))
}
stopCluster(cl)
unregister_dopar()

summary(per)
plot(per[,1])
plot(per[,2])
summary(gri)
plot(gri[,1])
plot(gri[,2])

plot(sqrt(pl[[1]][,1]))
plot(sqrt(gl[[1]][,1]))

plot(sqrt(pl[[2]][,1]))
plot(sqrt(gl[[2]][,1]))

plot(sqrt(pl[[1]][,2]))
plot(sqrt(gl[[1]][,2]))

plot(sqrt(pl[[2]][,2]))
plot(sqrt(gl[[2]][,2]))
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
mod = randomForest::randomForest(y ~ ., dfc, importance = T)
mod$importance[,1]

plot(0:7, rev(sqrt(pmax(mod$importance[,1], 0))))

pfun <- function(object, newdata) {
  stats::predict(object, newdata = newdata)
}

vip::list_metrics()
visCancer <- vip::vi(mod, method = "permute", train = dfc,
          target = "y", metric = "bal_accuracy",
          pred_wrapper = pfun, nsim = 25)
vip::vip(visCancer, geom = "boxplot")
# Shap #
# rf_unified <- treeshap::randomForest.unify(mod, dfc)
# rf_res <- treeshap(rf_unified, dfc)
# shap = as.data.frame(rf_res$shaps)
# 
# # LIME #
# rt = caret::train(dfc[, 1:3], dfc[[4]], method = "rf")
# explanation <- lime(dfc[, 1:3], rt, bin_continuous = T, n_bins = 20, use_density = T)
# elim = explain(dfc[, 1:3], explanation, labels = "1", n_features = 3)
# 
# lime = elim %>% dplyr::select(case, feature, feature_weight) %>% 
#   pivot_wider(names_from = feature, values_from = c(feature_weight)) %>% 
#   dplyr::select(-case) %>% as.data.frame()
# End #
```

```{r, warning=FALSE, message=FALSE, eval=FALSE, echo=FALSE}
library(pdp)
pvv = pdp::partial(mod, pred.var = c("v1", "v2"), prob = T, which.class = "1")
pv = pvv
pe = pv
pv$v1 = round(pv$v1, 2)
pv$v2 = round(pv$v2, 2)

pv1 = pv %>% group_by(v1) %>% summarise(yhat = sum(yhat))
pv2 = pv %>% group_by(v2) %>% summarise(yhat = sum(yhat))
sv = sum(pv$yhat)
pv$expect = rep(pv2$yhat, each = 51) * pv1$yhat / sv
pe$yhat = pv$expect

x = sum((pv$yhat*length(dfc$y) - pv$expect*length(dfc$y))^2 / (pv$expect*length(dfc$y)))
pchisq(x, df = 50*50, lower.tail = F)

pdp::plotPartial(pvv)
pdp::plotPartial(pe)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
set.seed(123)

xl = global_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, 
                       nsim = 10, folds = 5)
xl$global_imp
plot(0:7, rev(sqrt(pmax(xl$global_imp, 0))))


xg = global_grid_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, nsim = 10,
                       folds = 5, quantile_grid = TRUE)
xg$global_imp
plot(0:7, rev(sqrt(pmax(xg$global_imp, 0))))

d1 = data.frame(v1 = dfc[,1], CLIP = xl$local_imp$v1, 
                CLIQUE = xg$local_imp$v1,
                SHAP = shap$v1, LIME = lime$v1)

ggpairs(d1, mapping = aes(color = dfc$y))

ggpairs(d1, mapping = aes(color = z1))
ggpairs(d1, mapping = aes(color = z2))


gq = ggplot(d1, aes(x = v1, y = CLIQUE, color = z2)) +
  geom_point() + ylim(-0.05, 1)
gp = ggplot(d1, aes(x = v1, y = CLIP, color = z2)) +
  geom_point() + ylim(-0.05, 1)
gs = ggplot(d1, aes(x = v1, y = SHAP, color = z2)) +
  geom_point() + ylim(-0.6, 0.4)
gl = ggplot(d1, aes(x = v1, y = LIME, color = z2)) +
  geom_point() + ylim(-0.6, 0.4)

#library(patchwork)

gl + gs + gp + gq + 
  plot_layout(guides = "collect", axis_titles = "collect") &
  ggeasy::easy_add_legend_title("v2 > -1/3")


ggsave("xor2patch.pdf", dpi = 1600, width = 6.3, height = 4.5)

# ggpairs(d1, mapping = aes(color = 1:404 < 401))

# d2 = data.frame(v = dfc[,2], perm = xl$local_imp$v2,
#                 grid = xg$local_imp$v2,
#                 shap = shap$v2, lime = lime$v2)
# ggpairs(d2, mapping = aes(color = dfc$y))
# ggpairs(d2, mapping = aes(color = 1:404 < 401))

d3 = data.frame(v = dfc[,3], #perm = xl$local_imp$v3,
                grid = xg$local_imp$v3,
                shap = shap$v3, lime = lime$v3)

# ggpairs(d3, mapping = aes(color = 1:404 < 401))
```

```{r, echo=FALSE, eval=FALSE}
lmr1 = lm(as.numeric(y) ~ ., data = dfc[z2 == T, ])
s1 = summary(lmr1)
s1

lmr2 = lm(as.numeric(y) ~ ., data = dfc[z2 == F, ])
s2 = summary(lmr2)
s2
```


```{r, warning=FALSE, message=FALSE, echo=FALSE, eval=FALSE}
tuneGrid <- expand.grid(mtry = 2)
pd = data.frame(mat.or.vec(10, 3))
colnames(pd) = 0:2
gd = pd
k = 1
for(i in c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)){
  xl = local_perm_imp_cv(formula = y ~ ., data = dfc[1:400, ], 
                       method = "rf", tuneGrid = tuneGrid, 
                       nsim = i, k = 5)

  xg = local_grid_imp_cv(formula = y ~ ., data = dfc[1:400, ], 
                         method = "rf", tuneGrid = tuneGrid, nsim = i,
                         k = 5, quantile_grid = FALSE)
  
  d1 = data.frame(values = dfc[1:400, 1], perm = xl$local_imp$v1, 
                  grid = xg$local_imp$v1)
  print(ggpairs(d1, mapping = aes(color = sup[1:400])))
  
  l = data.frame(perm = xl$local_imp$v1, grid = xg$local_imp$v1)
  l$group = sup[1:400]
  j = data.frame(l %>% group_by(group) %>% summarise(p_mid = round(median(perm), 4),
                                    g_mid = round(median(grid), 4),
                                    p_spread = round(mad(perm), 4),
                                    g_spread = round(mad(grid), 4)))
  print(j)
  pd[k, ] = j$p_spread
  gd[k, ] = j$g_spread
  k = k + 1
}

pd$nsim = c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)
pdl = pivot_longer(pd, 1:3, names_to = "group", values_to = "value")
gd$nsim = c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)
gdl = pivot_longer(gd, 1:3, names_to = "group", values_to = "value")

bdl = pdl
colnames(bdl)[3] = "perm"
bdl$grid = gdl$value
bd = pivot_longer(bdl, 3:4, names_to = "type", values_to = "value")

ggplot(bd, aes(x = nsim, y = value, col = group)) + 
  geom_line() + geom_point() + facet_wrap(vars(type))

ggplot(bd, aes(x = nsim, y = value, col = type)) + 
  geom_line() + geom_point() + facet_wrap(vars(group))
```
