---
title: "local_imp_functions"
author: "Kelvyn Bladen"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(fastDummies)
library(caret)
library(rpart)
library(tidyverse)
library(GGally)
library(treeshap)
library(lime)
library(patchwork)
library(tictoc)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
tuneGrid = NULL
local_perm_imp_cm <- function(formula = medv ~ ., data = Boston, 
                              method = "ranger", tuneGrid = tuneGrid, 
                              nsim = 25, folds = 5) {
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  nr <- nrow(x)
  
  if (is(y, "factor")) {
    y = factor(y, labels = make.names(levels(y)))
  }
  
  set.seed(123)
  flds <- caret::createFolds(y, k = folds, returnTrain = T)
  set.seed(123)
  flds0 <- caret::createFolds(y, k = folds, list = F, returnTrain = F)
  
  model <- caret::train(x, y, 
                 # formula, data = data,
                 method = method,
                 tuneGrid = tuneGrid,
                 trControl = trainControl(method = "cv",
                                          index = flds,
                                          savePredictions = "final",
                                          classProbs = T))
  
  mods = list()
  for(i in 1:folds){
    mods[[i]] <- caret::train(x[flds0 != i,], y[flds0 != i], 
                 # formula, data = data,
                 method = method,
                 tuneGrid = model$finalModel$tuneValue,
                 trControl = trainControl(method = "none", classProbs = T))
  }
  
  
  output = list()
  output$bestTune = model$bestTune
  output$results = model$results
  output$finalModel = model$finalModel

  model$pred = model$pred %>% arrange(rowIndex)

  x_loc <- x
  x_loc[, ] <- 0
  x_temp <- x_loc

  if (!is(y, "factor")) {
    p = model$pred$pred
    truth = model$pred$obs
    m <- (truth - p)^2
  } else {
    truth <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    p = model$pred %>% dplyr::select(levels(y))
    m <- rowMeans((truth - p)^2)
  }

  for (j in seq_len(nsim)) {
    for (i in seq_len(nc)) {
      x_new <- x
      x_new[, i] <- x[sample(1:nr), i]

      if (!is(y, "factor")) {
        pr <- truth
        for(k in 1:folds){
          pr[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,], type = "raw")
        }
        new_m <- (truth - pr)^2
      } else {
        pr <- truth
        for(k in 1:folds){
          pr[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,], 
                                    type = "prob")
        }
        new_m <- rowMeans((truth - pr)^2)
      }
      x_temp[, i] <- new_m - m
    }
    x_loc <- x_loc + x_temp / nsim
  }
  output$local_imp = x_loc
  return(output)
}
```

```{r, eval=FALSE, echo=FALSE}
unregister_dopar <- function() {
  env <- foreach:::.foreachGlobals
  rm(list=ls(name=env), pos=env)
}
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(randomForest)
library(tidyverse)
library(patchwork)
library(randomForestVIP)
library(caret)
library(scales)
library(ggeasy)

train_models <- function(x, y, folds, flds0, method, tuneGrid) { # caret
  models <- vector("list", length(folds))
  for (k in seq_len(folds)) {
    models[[k]] <- caret::train(
      x[flds0 != k, ], y[flds0 != k],
      method = method,
      tuneGrid = tuneGrid,
      trControl = caret::trainControl(method = "none",
        classProbs = TRUE)
    )
  }
  return(models)
}

# Helper function to generate grid values
generate_grid_values <- function(xi, y, nsim, quantile_grid) {
  if (!is.numeric(xi)) {
    grid_v <- round(nsim * table(y) / length(y))
    gd <- min(pracma::gcd(grid_v[1], grid_v))
    grid_vals <- (grid_v / gd) |> as.data.frame() |> uncount(Freq) |> pull(1)
  } else {
    grid_vals <- if (quantile_grid) {
      quantile(xi, probs = seq(0, 1, length = nsim)) # Quantile-based grid
    } else {
      seq(min(xi), max(xi), length = nsim) # Uniform grid
    }
  }
  grid_vals
}

# Update predictions and calculate errors
calculate_new_m1 <- function(grid_val, x, ii, mods, flds0, truth, typ,
                            predictions) {
  x_new <- x
  #x_new[, ii] <- grid_val
  x_new[, ii] <- x[sample(1:nrow(x)), ii]
  

  for (k in seq_along(mods)) {
    if(brier_score){
      predictions[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,],
                                         type = typ)
    } else {
      predictions[flds0 == k] = predict(mods[[k]], x_new[flds0 == k,],
                                        type = typ)
    }
  }
  predictions
  if(!is.factor(y)){
    return(abs(truth - predictions))
  } else if (brier_score){
    # Calculate the row-wise mean squared error
    return(rowMeans(abs(truth - predictions)))
  } else {
    return(as.numeric(truth != predictions))
  }
}

get_var_loc1 <- function(ii, x, y, truth, nsim, mods, flds0, m, typ,
                  quantile_grid, predictions) { # depends on y

  # Generate grid values for the selected variable
  grid_vals <- generate_grid_values(x[, ii], y, nsim, quantile_grid)

  # Apply over all grid values
  new_m_mat <- sapply(grid_vals, calculate_new_m1, x = x, ii = ii,
                      mods = mods, flds0 = flds0, truth = truth, typ = typ,
                      predictions = predictions)

  # Calculate the mean error for each observation and adjust by baseline errors
  rowMeans(new_m_mat) - m
}


# Main function
local_perm_imp_cm <- function(formula = medv ~ ., data = Boston,
                   method = "rf", tuneGrid = tuneGrid,
                   parallel = TRUE, cores = 5, seed = 123,
                   nsim = 25, folds = 5, quantile_grid = TRUE,
                   brier_score = TRUE) {
  # Set up the data
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  if (is.factor(y)) {
    y <- factor(y, labels = make.names(levels(y)))
  }

  # Set up cross-validation folds
  set.seed(seed)
  flds <- caret::createFolds(y, k = folds, returnTrain = TRUE)
  set.seed(seed)
  flds0 <- caret::createFolds(y, k = folds, list = FALSE, returnTrain = FALSE)

  # Train the global model
  global_model <- caret::train(
    x, y,
    method = method,
    tuneGrid = tuneGrid,
    trControl = trainControl(
      method = "cv",
      index = flds,
      savePredictions = "final",
      classProbs = TRUE
    )
  )


  # Parallel setup
  if (parallel) {
    cl <- parallel::makeCluster(cores)
    doParallel::registerDoParallel(cl)
    on.exit({
      parallel::stopCluster(cl)
      env <- foreach:::.foreachGlobals
      rm(list=ls(name=env), pos=env)
    })
  }

  # Train models for each fold
  mods <- train_models(x, y, folds, flds0, method,
                       global_model$finalModel$tuneValue)

  global_model$pred = global_model$pred %>% dplyr::arrange(rowIndex)

  # Calculate errors
  if (!is.factor(y)) {
    truth <- global_model$pred$obs
    predictions <- global_model$pred$pred
    m <- abs(truth - predictions)
  } else if (brier_score) {
    truth <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    predictions <- global_model$pred %>% dplyr::select(levels(y))
    m <- rowMeans(abs(truth - predictions))
  } else {
    truth <- global_model$pred$obs
    predictions <- global_model$pred$pred
    m <- as.numeric(truth != predictions)
  }

  # Task function for parallel computation
  x_loc <- future.apply::future_lapply(
    seq_len(nc),
    function(ii) {
      get_var_loc1(ii, x = x, y = y, truth = truth, nsim = nsim, mods = mods,
            flds0 = flds0, m = m, typ = ifelse(brier_score, "prob", "raw"),
            quantile_grid = quantile_grid, predictions = predictions)
    }
  ) %>% as.data.frame()
  colnames(x_loc) <- colnames(x)

  # Output
  list(
    bestTune = global_model$bestTune,
    results = global_model$results,
    finalModel = global_model$finalModel,
    local_imp = x_loc
  )
}
```


```{r, warning=FALSE, message=FALSE, echo=FALSE}
tuneGrid = NULL
local_grid_imp_cm <- function(formula = medv ~ ., 
                              x, y, data = Boston, 
                              method = "rf", tuneGrid = tuneGrid, 
                              nsim = 25, folds = 5, quantile_grid = TRUE) {
  model_frame <- model.frame(formula, data = data)
  x <- model_frame[, -1]
  y <- model_frame[, 1]
  nc <- ncol(x)
  
  if (is(y, "factor")) {
    y = factor(y, labels = make.names(levels(y)))
  }
  
  set.seed(123)
  flds <- caret::createFolds(y, k = folds, returnTrain = T)
  set.seed(123)
  flds0 <- caret::createFolds(y, k = folds, list = F, returnTrain = F)

  model <- caret::train(x, y, 
                 # formula, data = data,
                 method = method,
                 tuneGrid = tuneGrid,
                 trControl = trainControl(method = "cv",
                                          index = flds,
                                          savePredictions = "final",
                                          classProbs = T))
  
  mods = vector("list", folds)
  for(k in 1:folds){
    mods[[k]] <- caret::train(x[flds0 != k,], y[flds0 != k],
                 # formula, data = data,
                 method = method,
                 tuneGrid = model$finalModel$tuneValue,
                 trControl = trainControl(method = "none", classProbs = T))
  }
  
  output = list()
  output$bestTune = model$bestTune
  output$results = model$results
  output$finalModel = model$finalModel

  model$pred = model$pred |> arrange(rowIndex)

  x_loc <- x
  x_loc[, ] <- 0

  if (!is(y, "factor")) {
    truth = model$pred$obs
    p = model$pred$pred
    m <- (truth - p)^2
  } else {
    truth <- fastDummies::dummy_cols(as.data.frame(y))[, -1]
    p = model$pred |> dplyr::select(levels(y))
    m <- rowMeans((truth - p)^2)
  }
  
  # add parallelization or vectorization via mclapply for this for loop!!!!
  
  for (i in seq_len(nc)) {
    if(!inherits(x[,i], "numeric")){
      # perhaps do a permutation for factors!
      # maybe convert factors to characters!
      
      # grid_v = round(nsim * table(y) / length(y))
      # gd = min(pracma::gcd(grid_v[1], grid_v))
      # grid_vals = (grid_v / gd) |> as.data.frame() |> uncount(Freq) |> pull(1)
      
      grid_vals = unique(x[,i])
    } else {
      grid_vals = ifelse(rep(quantile_grid, nsim),
      quantile(x[,i], probs = seq(0, 1, length = nsim)), #quantile
      seq(min(x[,i]), max(x[,i]), length = nsim)) #uniform
    }
    
    for (j in grid_vals) {
      x_new <- x
      x_new[, i] <- j

      pr <- as.data.frame(truth)
      
      typ = ifelse(!is(y, "factor"), "raw", "prob")
      
      for(k in 1:folds){
        pr[flds0 == k,] = predict(mods[[k]], x_new[flds0 == k,], type = typ)
      }
      
      new_m <- rowMeans((truth - pr)^2)
      
      x_loc[, i] <- x_loc[, i] + ((new_m - m) / nsim)
    }
    
  }
  output$local_imp = x_loc
  return(output)
}
```

```{r, eval=FALSE, echo=FALSE}
cl <- makeCluster(5)

# Export required objects to the cluster
clusterExport(cl, varlist = c("x", "flds0", "mods", "y", "m", "nsim", "yd", "folds", "i"))

# Parallelized grid search
x_loc[, i] <- rowSums(parLapply(cl, grid_vals, function(j) {
  x_new <- x
  x_new[, i] <- j

  if (!is(y, "factor")) {
    pr <- numeric(length(yd))
    pr <- unlist(lapply(1:folds, function(k) {
      predict(mods[[k]], x_new[flds0 == k, ], type = "raw")
    }))
    new_m <- (pr - yd)^2
  } else {
    pr <- matrix(0, nrow = nrow(yd), ncol = ncol(yd))
    pr <- do.call(rbind, lapply(1:folds, function(k) {
      predict(mods[[k]], x_new[flds0 == k, ], type = "prob")
    }))
    new_m <- rowMeans((yd - pr)^2)
  }

  ((new_m - m) / nsim)
}))

# Stop the cluster
stopCluster(cl)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
source("clique.R")
```

\newpage
# Data

```{r, message=FALSE, warning=FALSE}
n <- 400 # increase higher 1000

set.seed(123)

v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)
# v4 = factor(rbinom(n, size = 1, prob = 0.5))
# v5 = factor(rbinom(n, size = 1, prob = 0.5))

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)

dfc <- data.frame(v1, v2, v3, y)

# dfc = rbind(dfc, 
#             c(3/4, 3/4, -2/3, 0), 
#             c(-3/4, 3/4, 1/3, 1),
#             c(3/4, -3/4, 2/3, 1),
#             c(-3/4, -3/4, -1/3, 1))

z1 = factor(dfc$v1 > -1/3)
z2 = factor(dfc$v2 > -1/3)

sup = factor(ifelse(z2 == F, 0, ifelse(z1 == F, 2, 1)))


ggdat = ggplot(dfc, aes(v1, v2, colour = y)) + geom_point(size = 2) +
  scale_color_manual(values = c("#2CA02C", "#9467BD"))
ggdat
# ggsave("inst/plots/xor2_dat1.jpg", dpi = 800, width = 3.6, height = 2.5) 

# ggplot(dfc, aes(v1, v2, colour = sup)) + geom_point(size = 2)
# ggsave(inst/plots/"xor2.pdf", dpi = 800, width = 4, height = 2.5)



set.seed(1234)

v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)
# v4 = factor(rbinom(n, size = 1, prob = 0.5))
# v5 = factor(rbinom(n, size = 1, prob = 0.5))

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)

dft <- data.frame(v1, v2, v3, y)

z1t = factor(dft$v1 > -1/3)
z2t = factor(dft$v2 > -1/3)
```

\newpage
# Training Local Importance

```{r, warning=FALSE, message=FALSE}
tic()
class_mod = randomForest::randomForest(y ~ ., dfc)

# Shap #

rf_unified <- treeshap::randomForest.unify(class_mod, dfc)
rf_res <- treeshap(rf_unified, dfc, interactions = T)
shap = as.data.frame(rf_res$shaps)
toc()

########################################
rf_res$interactions
dd = as.data.frame(rf_res$interactions)
rf_res$interactions[,,1]
colSums(rf_res$interactions[,,1])
rf_res$shaps[1,]
dim(rf_res$interactions)


feature_names <- c("A", "B", "C")
# Convert array into a list of matrices (one per sample)
shap_list <- lapply(1:400, function(i) {
    df <- as.data.frame(rf_res$interactions[,,i])
    df <- reshape2::melt(df, value.name = "SHAP_Interaction")
    df$Sample <- i  # Add sample index
    return(df)
})


# Combine into a single dataframe
shap_df <- bind_rows(shap_list)

shap_df$var2 = paste0("v", 1:3)
shap_df


shap_df %>% group_by(variable, var2) %>% 
  summarise(SHAP_Interaction = mean(SHAP_Interaction))

pivot_longer(dfc, 1:3)

########################################

# LIME #
tic()
rt = caret::train(dfc[, 1:3], dfc[[4]], method = "rf")
explanation <- lime(dfc[, 1:3], rt, bin_continuous = T, n_bins = 20, 
                    use_density = T)

elim = explain(dfc[, 1:3], explanation, labels = "1", n_features = 3)

lime = elim %>% dplyr::select(case, feature, feature_weight) %>% 
  pivot_wider(names_from = feature, values_from = c(feature_weight)) %>% 
  dplyr::select(-case) %>% as.data.frame()
toc()

# End #
```

```{r, warning=FALSE, message=FALSE, eval=FALSE, echo=FALSE}
library(pdp)
pvv = pdp::partial(class_mod, pred.var = c("v1", "v2"), 
                   prob = T, which.class = "1")
pv = pvv
pe = pv
pv$v1 = round(pv$v1, 2)
pv$v2 = round(pv$v2, 2)

pv1 = pv %>% group_by(v1) %>% summarise(yhat = sum(yhat))
pv2 = pv %>% group_by(v2) %>% summarise(yhat = sum(yhat))
sv = sum(pv$yhat)
pv$expect = rep(pv2$yhat, each = 51) * pv1$yhat / sv
pe$yhat = pv$expect

x = sum((pv$yhat*length(dfc$y) - pv$expect*length(dfc$y))^2 /
          (pv$expect*length(dfc$y)))
pchisq(x, df = 50*50, lower.tail = F)

pdp::plotPartial(pvv)
pdp::plotPartial(pe)
```

\newpage
# ICI

```{r}
library(mlbench)
library(featureImportance)
library(mlr)

# Create a regression task
task1 = mlr::makeClassifTask(data = dfc, target = "y")
learner <- mlr::makeLearner("classif.randomForest")
model <- mlr::train(learner, task1)

# Compute feature importance
ici <- featureImportance::featureImportance(model, data = dfc, target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

# View results
print(ici)

ici$importance

pi.curve = plotImportance(ici, feat = "v1", mid = "mmce", 
                          individual = FALSE, hline = TRUE)
ici.curves = plotImportance(ici, feat = "v1", mid = "mmce", 
                            individual = TRUE, hline = FALSE)

pi.curve$data = pi.curve$data |> arrange(replace.id)
ici.curves$data = ici.curves$data |> arrange(replace.id)
pi.curve + aes(color = z1)
pi.curve + aes(color = z2) + scale_y_continuous(limits = c(-0.05, 1))

ici.curves + aes(color = z1)
ici.curves + aes(color = z2)

pi.curve + ici.curves + plot_layout(axes = "collect")

iii = ici$importance |> 
  pivot_wider(id_cols = c(row.id, n.feat.perm), names_from = features, 
              values_from = mmce) |>
  group_by(row.id) |>
  summarize(v1 = mean(v1), v2 = mean(v2), v3 = mean(v3)) |>
  dplyr::select(!row.id)
iii

ggplot(dfc, aes(x = v1, y = iii$v1)) +
  geom_point() + ylim(-0.05, 1)
ggplot(dfc, aes(x = v1, y = iii$v1, color = factor(z2))) +
  geom_point() + ylim(-0.05, 1)


iii = ici$importance |> 
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mmce) |>
  group_by(replace.id) |>
  summarize(v1 = mean(v1), v2 = mean(v2), v3 = mean(v3)) |>
  dplyr::select(!replace.id)

ggplot(dfc, aes(x = v1, y = iii$v1)) +
  geom_point() + ylim(-0.05, 1)

ggplot(dfc, aes(x = v1, y = iii$v1, color = factor(z2))) +
  geom_point() + ylim(-0.05, 1)
#kkkk


# Compute feature importances for pre-known groups
rr2 = row.names(dfc[z2 == T, ]) |> as.numeric()
nrr2 = row.names(dfc[z2 == F, ]) |> as.numeric()

ic1 <- featureImportance(model, data = dfc[z2 == T, ], target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

pi.curve1 = plotImportance(ic1, feat = "v1", mid = "mmce", 
                          individual = FALSE, hline = F)

i1 = ic1$importance |>
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mmce) |>
  group_by(replace.id) |>
  summarize(v1 = mean(v1), v2 = mean(v2), v3 = mean(v3)) # |>
  # dplyr::select(!replace.id)
i1$replace.id = rr2

ic2 <- featureImportance(model, data = dfc[z2 == F, ], target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

pi.curve2 = plotImportance(ic2, feat = "v1", mid = "mmce", 
                          individual = FALSE, hline = F)

i2 = ic2$importance |> 
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mmce) |>
  group_by(replace.id) |>
  summarize(v1 = mean(v1), v2 = mean(v2), v3 = mean(v3)) #|>
  # dplyr::select(!replace.id)

i2$replace.id = nrr2

ii = as.data.frame(rbind(i1, i2)) |> arrange(replace.id)

ggplot(dfc, aes(x = v1, y = ii$v1, color = factor(z2))) +
  geom_point()

pi.curve1 + ylim(0, 1) + pi.curve2 + ylim(0, 1) + plot_layout(axes = "collect")
```


\newpage
# CV Training

```{r, warning=FALSE, message=FALSE}
set.seed(123)
tic()
xl = local_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, 
                       nsim = 25, folds = 5)
toc()
# xl$local_imp
tic()
xg = local_grid_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = NULL, nsim = 25,
                       folds = 5, quantile_grid = TRUE)
toc()
# xg$local_imp

tic()
xg1 = clique(formula = y ~ ., data = dfc, parallel = T, cores = 5, seed = 123,
            method = "rf", tuneGrid = NULL, 
            nsim = 25, folds = 5, quantile_grid = TRUE, brier_score = T)
tictoc::toc()

d1 = data.frame(v1 = dfc[,1], CLIP = xl$local_imp$v1, 
                CLIQUE_old = xg$local_imp$v1,
                CLIQUE = xg1$local_imp$v1,
                ICI = iii$v1,
                SHAP = shap$v1, LIME = lime$v1)

ggplot(d1, aes(x = CLIQUE_old, y = CLIQUE, color = z2)) +
  geom_point() + geom_abline()

ggpairs(d1, mapping = aes(color = dfc$y))

#ggpairs(d1, mapping = aes(color = z1))
ggpairs(d1, mapping = aes(color = z2))

gq = ggplot(d1, aes(x = v1, y = CLIQUE, color = z2)) +
  geom_point() + ylim(-0.1, 1)
gp = ggplot(d1, aes(x = v1, y = CLIP, color = z2)) +
  geom_point() + ylim(-0.1, 1) +
  ylab("Local Permute")
gs = ggplot(d1, aes(x = v1, y = SHAP, color = z2)) +
  geom_point() + ylim(-0.6, 0.4)
gl = ggplot(d1, aes(x = v1, y = LIME, color = z2)) +
  geom_point() + ylim(-0.6, 0.4)

gi = ggplot(d1, aes(x = v1, y = ICI, color = z2)) +
  geom_point() + ylim(-0.1, 1)
gi

gi + gp + gq + 
  plot_layout(guides = "collect", axes = "collect", axis_titles = "collect")
#library(patchwork)

patch = gl + gs + gp + gq + 
  plot_layout(guides = "collect", axes = "collect", 
              axis_titles = "collect") &
  ggeasy::easy_add_legend_title("v2 > -1/3") &
  scale_color_manual(values = c("#F8766D", "#01ADD8"))
patch

patch = ggdat + gl + gs + gi + gp + gq + 
  plot_layout(guides = "collect", axes = "collect_x", 
              axis_titles = "collect") &
  ggeasy::easy_add_legend_title("v2 > -1/3") &
  scale_color_manual(values = c("#F8766D", "#01ADD8"))
patch

patch[[1]] = patch[[1]] + scale_color_manual(values = c("#2CA02C", "#9467BD")) +
  ggeasy::easy_add_legend_title("y")
patch

ggsave("inst/plots/xor2patch_abs.jpg", dpi = 2400, width = 6.8, height = 4)

ggsave("inst/plots/xor2patch_poster_c.jpg", dpi = 2400, width = 5.6, height = 4)
ggsave("inst/plots/xor2patch_poster.jpg", dpi = 2400, width = 5.6, height = 4)
ggsave("inst/plots/xor2patch_poster.jpg", dpi = 2400, width = 6.3, height = 4.5)


patch = gl + gs + gi + gq + 
  plot_layout(guides = "collect", axes = "collect", 
              axis_titles = "collect") &
  ggeasy::easy_add_legend_title("v2 > -1/3") #&
  #scale_color_manual(values = c("#F8766D", "#01ADD8"))
patch & ggeasy::easy_move_legend("bottom")
ggsave("inst/plots/xor2patch_newi.jpg", dpi = 1200, width = 4.4, height = 4.4)
# ggsave("inst/plots/xor2patch_newi.jpg", dpi = 1200, width = 5.6, height = 4)

patch
ggsave("inst/plots/xor2patch_newi_1col.jpg", dpi = 1200, 
       width = 5.5, height = 3.3)


ggdat + patch + 
  plot_layout(widths = c(10, 12))

ggsave("inst/plots/xor_1col.pdf", dpi = 1600, width = 8.8, height = 3.3)


# ggpairs(d1, mapping = aes(color = 1:404 < 401))

# d2 = data.frame(v = dfc[,2], perm = xl$local_imp$v2,
#                 grid = xg$local_imp$v2,
#                 shap = shap$v2, lime = lime$v2)
# ggpairs(d2, mapping = aes(color = dfc$y))
# ggpairs(d2, mapping = aes(color = 1:404 < 401))

d3 = data.frame(v = dfc[,3], #perm = xl$local_imp$v3,
                grid = xg$local_imp$v3,
                shap = shap$v3, lime = lime$v3)

# ggpairs(d3, mapping = aes(color = 1:404 < 401))
```


```{r}
d1 = d1 |> select(-CLIP)
sc = apply(d1, 2, FUN = function(x){max(abs(x))})
vr = d1 |> filter(z2 == F)

mae = colMeans(abs(vr / sc))
rmse = sqrt(colMeans((vr / sc)^2))
mae
rmse
```


```{r}
lmr1 = lm(as.numeric(y) ~ ., data = dfc[z2 == T, ])
s1 = summary(lmr1)
s1

lmr2 = lm(as.numeric(y) ~ ., data = dfc[z2 == F, ])
s2 = summary(lmr2)
s2
```


```{r, warning=FALSE, message=FALSE, eval=FALSE, echo=FALSE}
tuneGrid <- expand.grid(mtry = c(1,2,3))
pd = data.frame(mat.or.vec(10, 3))
colnames(pd) = 0:2
gd = pd
k = 1
mm = list()

for(i in c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)){
  xl = local_perm_imp_cm(formula = y ~ ., data = dfc[1:400, ], 
                       method = "rf", tuneGrid = tuneGrid, 
                       nsim = i, folds = 5)

  xg = local_grid_imp_cm(formula = y ~ ., data = dfc[1:400, ], 
                         method = "rf", tuneGrid = tuneGrid, nsim = i,
                         folds = 5, quantile_grid = T)
  
  d1 = data.frame(values = dfc[1:400, 1], perm = xl$local_imp$v1, 
                  grid = xg$local_imp$v1)
  #print(ggpairs(d1, mapping = aes(color = sup[1:400])))
  
  l = data.frame(perm = xl$local_imp$v1, grid = xg$local_imp$v1)
  l$group = sup[1:400]
  
  l$m = i
  mm[[k]] = l
  
  j = data.frame(l %>% group_by(group) %>% 
                   summarise(p_mid = round(median(perm), 4),
                             g_mid = round(median(grid), 4),
                             p_spread = round(mad(perm), 4),
                             g_spread = round(mad(grid), 4)))
  print(j)
  pd[k, ] = j$p_spread
  gd[k, ] = j$g_spread
  k = k + 1
}

pd$nsim = c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)
pdl = pivot_longer(pd, 1:3, names_to = "group", values_to = "value")
gd$nsim = c(1, 3, 5, 10, 15, 20, 30, 50, 75, 100)
gdl = pivot_longer(gd, 1:3, names_to = "group", values_to = "value")

bdl = pdl
colnames(bdl)[3] = "perm"
bdl$grid = gdl$value
bd = pivot_longer(bdl, 3:4, names_to = "type", values_to = "value")

ggplot(bd, aes(x = nsim, y = value, col = group)) + 
  geom_line() + geom_point() + facet_wrap(vars(type))

ggplot(bd, aes(x = nsim, y = value, col = type)) + 
  geom_line() + geom_point() + facet_wrap(vars(group))

bg = bd %>% filter(type == "grid")

ggplot(bg, aes(x = nsim, y = value, col = group)) + 
  geom_line() + geom_point()

ggplot(bg, aes(x = nsim, y = value, col = type)) + 
  geom_line() + geom_point()


mm[[2]]$grid
mmm = rbind(mm[[1]], mm[[2]], mm[[3]], mm[[4]], mm[[5]],
      mm[[6]], mm[[7]], mm[[8]], mm[[9]], mm[[10]])

ggplot(mmm, aes(x = m, y = grid, col = group)) + 
  geom_point(position = position_jitter(width = 0.07)) +
  geom_hline(yintercept = 2/3, color = "blue") +
  geom_hline(yintercept = 1/3, color = "green")
```


```{r, warning=FALSE, message=FALSE}
n <- 400 # increase higher 1000
set.seed(444) # 123
v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)
dfc <- data.frame(v1, v2, v3, y)

z1 = factor(dfc$v1 > -1/3)
z2 = factor(dfc$v2 > -1/3)
sup = factor(ifelse(z2 == F, 0, ifelse(z1 == F, 2, 1)))



table(dfc$y)
table(z1) / 400
table(sup)[2:3] / (sum(table(sup)[2:3]))

tuneGrid <- expand.grid(mtry = 2)
pd = data.frame(mat.or.vec(20, 3))
colnames(pd) = 0:2
gd = pd
k = 1
mm = list()

ptimes = vector(length = 20)
qtimes = vector(length = 20)

for(i in 1:20){
  
  s = Sys.time()
  xl = local_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = tuneGrid, 
                       nsim = i, folds = 5)
  ptimes[i] = Sys.time() - s

  s1 = Sys.time()
  xg = local_grid_imp_cm(formula = y ~ ., data = dfc, 
                         method = "rf", tuneGrid = tuneGrid, 
                         nsim = i, folds = 5, quantile_grid = T)
  qtimes[i] = Sys.time() - s1
  
  # d1 = data.frame(values = dfc[, 1], perm = xl$local_imp$v1, 
  #                 grid = xg$local_imp$v1)
  # print(ggpairs(d1, c(1, 3), mapping = aes(color = sup)))
  
  l = data.frame(perm = xl$local_imp$v1, grid = xg$local_imp$v1)
  l$group = sup
  
  l$m = i
  mm[[k]] = l
  
  j = data.frame(l %>% group_by(group) %>% 
                   summarise(p_mid = round(median(perm), 4),
                             g_mid = round(median(grid), 4),
                             p_spread = round(mad(perm), 4),
                             g_spread = round(mad(grid), 4)))
  #print(j)
  pd[k, ] = j$p_spread
  gd[k, ] = j$g_spread
  k = k + 1
}

# ptimes
# qtimes
# ggplot(mapping = aes(x = 1:20, y = ptimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 15), breaks = c(0, 4, 8, 12))
# ggplot(mapping = aes(x = 1:20, y = qtimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 15), breaks = c(0, 4, 8, 12))

dat = data.frame(M = 1:20, ptimes, qtimes)
dat = dat %>% pivot_longer(cols = 2:3)

ggplot(dat, aes(x = M, y = value, colour = name, group = name)) + 
  geom_point() + 
  geom_line() +
  scale_x_continuous(limits = c(0, 20.1)) +
  scale_y_continuous(limits = c(0, 3), breaks = c(0, 1, 2, 3))


# pd$nsim = 1:20
# pdl = pivot_longer(pd, 1:3, names_to = "group", values_to = "value")
# gd$nsim = 1:20
# gdl = pivot_longer(gd, 1:3, names_to = "group", values_to = "value")
#
# bdl = pdl
# colnames(bdl)[3] = "perm"
# bdl$grid = gdl$value
# bd = pivot_longer(bdl, 3:4, names_to = "type", values_to = "value")
# 
# ggplot(bd, aes(x = nsim, y = value, col = group)) + 
#   geom_line() + geom_point() + facet_wrap(vars(type))
# 
# ggplot(bd, aes(x = nsim, y = value, col = type)) + 
#   geom_line() + geom_point() + facet_wrap(vars(group))


mmm = rbind(mm[[1]], mm[[2]], mm[[3]], mm[[4]], mm[[5]],
      mm[[6]], mm[[7]], mm[[8]], mm[[9]], mm[[10]],
      mm[[11]], mm[[12]], mm[[13]], mm[[14]], mm[[15]],
      mm[[16]], mm[[17]], mm[[18]], mm[[19]], mm[[20]])

gg = ggplot(mmm, aes(x = m, y = grid, col = group)) + 
  geom_point(position = position_jitter(width = 0.2)) +
  ylab("CLIQUE") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

# m1 = mmm %>% filter(m == 1)
# 
# ggplot(m1, aes(x = perm, y = grid, colour = group)) + 
#   geom_point() +
#   geom_hline(yintercept = c(0, .349, .651))

# hline <- data.frame(
#   group = factor(0:2),  # Match the facet variable
#   y = c(0, .349, .651)  # Different hline values for each facet
# )

# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group), ncol = 1)
# 
# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group))


gp = ggplot(mmm, aes(x = m, y = perm, col = group)) + 
  geom_point(position = position_jitter(width = 0.07)) +
  ylab("CLIP") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

gp + gg + plot_layout(guides = "collect", axes = "collect")


mm1 = mmm %>% group_by(group, m) %>% summarise(p_max = max(perm),
                                         p_min = min(perm),
                                         g_max = max(grid),
                                         g_min = min(grid),
                                         perm = median(perm),
                                         grid = median(grid))

g1 = ggplot(mm1, aes(x = m, y = grid, col = group)) + 
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

p1 = ggplot(mm1, aes(x = m, y = perm, col = group)) + 
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

g1 + p1 + plot_layout(guides = "collect", axes = "collect")


g1 = ggplot(mm1, aes(x = m, y = grid, col = group)) + 
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = g_min, ymax = g_max)) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

p1 = ggplot(mm1, aes(x = m, y = perm, col = group)) + 
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = p_min, ymax = p_max), position = "dodge") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

g1 + p1 + plot_layout(guides = "collect", axes = "collect")

?geom_boxplot()
# ggplot(mmm, aes(x = m, y = perm, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(yintercept = c(0, 1/3, 2/3)) + 
#   scale_x_continuous(breaks = 1:20) + facet_wrap(vars(group))
```


```{r, warning=FALSE, message=FALSE}
n <- 400 # increase higher 1000
set.seed(444) # 123
v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)
dfc <- data.frame(v1, v2, v3, y)

z1 = factor(dfc$v1 > -1/3)
z2 = factor(dfc$v2 > -1/3)
sup = factor(ifelse(z2 == F, "C", ifelse(z1 == F, "A", "B")))


gy = ggplot(dfc, aes(v1, v2, colour = y)) + geom_point() +
  scale_color_manual(values = c("#2CA02C", "#9467BD"))
gr = ggplot(dfc, aes(v1, v2, colour = sup)) + geom_point() +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))



table(dfc$y)
table(z1) / 400
table(sup)[2:3] / (sum(table(sup)[2:3]))

tuneGrid <- expand.grid(mtry = 2)
pd = data.frame(mat.or.vec(11, 3))
colnames(pd) = 0:2
gd = pd
k = 1
mm = list()

ptimes = vector(length = 11)
qtimes = vector(length = 11)

for(i in c(2, 1:10 * 5)){
  
  s = Sys.time()
  xl = local_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = tuneGrid, 
                       nsim = i, folds = 5)
  ptimes[k] = Sys.time() - s

  s1 = Sys.time()
  # xg = local_grid_imp_cm(formula = y ~ ., data = dfc, 
  #                        method = "rf", tuneGrid = tuneGrid, 
  #                        nsim = i, folds = 5, quantile_grid = T)
    # xg = clique(formula = y ~ ., data = dfc, 
    #                      method = "rf", tuneGrid = tuneGrid, 
    #                      nsim = i, folds = 5, quantile_grid = T)
    xg = clique(formula = y ~ ., data = dfc, parallel = T, cores = 5, 
                seed = 123, method = "rf", tuneGrid = NULL, 
                nsim = i, folds = 5, quantile_grid = TRUE, brier_score = T)
  qtimes[k] = Sys.time() - s1
  
  # d1 = data.frame(values = dfc[, 1], perm = xl$local_imp$v1, 
  #                 grid = xg$local_imp$v1)
  # print(ggpairs(d1, c(1, 3), mapping = aes(color = sup)))
  
  l = data.frame(perm = xl$local_imp$v1, grid = xg$local_imp$v1)
  l$group = sup
  
  l$m = i
  mm[[k]] = l
  
  j = data.frame(l %>% group_by(group) %>% 
                   summarise(p_mid = round(median(perm), 4),
                             g_mid = round(median(grid), 4),
                             p_spread = round(mad(perm), 4),
                             g_spread = round(mad(grid), 4)))
  #print(j)
  pd[k, ] = j$p_spread
  gd[k, ] = j$g_spread
  k = k + 1
  print(k)
}

# ptimes
# qtimes
# ggplot(mapping = aes(x = 1:20, y = ptimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 15), breaks = c(0, 4, 8, 12))
# ggplot(mapping = aes(x = 1:20, y = qtimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 15), breaks = c(0, 4, 8, 12))

dat = data.frame(M = 1:11, ptimes, qtimes)
dat = dat %>% pivot_longer(cols = 2:3)

ggplot(dat, aes(x = M, y = value, colour = name, group = name)) + 
  geom_point() + 
  geom_line() +
  scale_x_continuous(limits = c(0, 17.1)) +
  scale_y_continuous(limits = c(0, 4.8), breaks = c(0, 1, 2, 3, 4))


# pd$nsim = 1:20
# pdl = pivot_longer(pd, 1:3, names_to = "group", values_to = "value")
# gd$nsim = 1:20
# gdl = pivot_longer(gd, 1:3, names_to = "group", values_to = "value")
#
# bdl = pdl
# colnames(bdl)[3] = "perm"
# bdl$grid = gdl$value
# bd = pivot_longer(bdl, 3:4, names_to = "type", values_to = "value")
# 
# ggplot(bd, aes(x = nsim, y = value, col = group)) + 
#   geom_line() + geom_point() + facet_wrap(vars(type))
# 
# ggplot(bd, aes(x = nsim, y = value, col = type)) + 
#   geom_line() + geom_point() + facet_wrap(vars(group))

mm[[1]] |> group_by(group) |> summarise(mean(grid))
mmm = rbind(mm[[1]], mm[[2]], mm[[3]], mm[[4]], mm[[5]],
      mm[[6]], mm[[7]], mm[[8]], mm[[9]], mm[[10]],
      mm[[11]]
      #, mm[[12]], mm[[13]], mm[[14]], mm[[15]],
      #mm[[16]], mm[[17]]
      #, mm[[18]], mm[[19]], mm[[20]]
      )

region = factor(case_when(
  mmm$group == 0 ~ "C",
  mmm$group == 1 ~ "B",
  mmm$group == 2 ~ "A",
))

gg = ggplot(mmm, aes(x = m, y = grid, col = group)) + 
  geom_point(position = position_jitter(width = 0.2)) +
  ylab("v1 CLIQUE") +
  xlab("Quantiles (M)") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(limits = c(0, 51), breaks = 0:5*10) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5) +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))

# m1 = mmm %>% filter(m == 1)
# 
# ggplot(m1, aes(x = perm, y = grid, colour = group)) + 
#   geom_point() +
#   geom_hline(yintercept = c(0, .349, .651))

# hline <- data.frame(
#   group = factor(0:2),  # Match the facet variable
#   y = c(0, .349, .651)  # Different hline values for each facet
# )

# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group), ncol = 1)
# 
# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group))


gp = ggplot(mmm, aes(x = m, y = perm, col = group)) + 
  geom_point(position = position_jitter(width = 0.07)) +
  ylab("v1 Local Permute") +
  xlab("Permutations (M)") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(limits = c(0, 51), breaks = 0:5*10) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5) +
  ggeasy::easy_add_legend_title("Region") +
  scale_color_manual(values = c("grey50", "#00BFC4", "#F8766D"))

#library(patchwork)
gy + gr + gp + gg + 
  plot_layout(guides = "collect", axes = "collect",
              heights = c(2, 3))


#ggsave("inst/plots/M_effect1.jpg", dpi = 1200, height = 5.5, width = 5.5)

gr + gp + gg + 
  plot_layout(guides = "collect", axes = "collect",
              widths = c(1,1,1))
ggsave("inst/plots/M_effect_w1.pdf", dpi = 1200, height = 2.4, width = 7.2)
5.5/(701/243)
mm1 = mmm %>% group_by(group, m) %>% summarise(p_max = max(perm),
                                         p_min = min(perm),
                                         g_max = max(grid),
                                         g_min = min(grid),
                                         perm = median(perm),
                                         grid = median(grid))

g1 = ggplot(mm1, aes(x = m, y = grid, col = group)) + 
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

p1 = ggplot(mm1, aes(x = m, y = perm, col = group)) + 
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

g1 + p1 + plot_layout(guides = "collect", axes = "collect")


g1 = ggplot(mm1, aes(x = m, y = grid, col = group)) + 
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = g_min, ymax = g_max)) +
  geom_line() +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

p1 = ggplot(mm1, aes(x = m, y = perm, col = group)) + 
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = p_min, ymax = p_max), position = "dodge") +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:10*2) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

g1 + p1 + plot_layout(guides = "collect", axes = "collect")

?geom_boxplot()
# ggplot(mmm, aes(x = m, y = perm, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(yintercept = c(0, 1/3, 2/3)) + 
#   scale_x_continuous(breaks = 1:20) + facet_wrap(vars(group))
```


```{r, warning=FALSE, message=FALSE}
n <- 200 # increase higher 1000
set.seed(444) # 123
v1 = runif(n, -1, 1)
v2 = runif(n, -1, 1)
v3 = runif(n, -1, 1)

y = ifelse(v1 < -1/3, 0, 
           ifelse(v2 > -1/3, 1, 0))
y = as.factor(y)
dfc <- data.frame(v1, v2, v3, y)

z1 = factor(dfc$v1 > -1/3)
z2 = factor(dfc$v2 > -1/3)
sup = factor(ifelse(z2 == F, 0, ifelse(z1 == F, 2, 1)))

ggplot(dfc, aes(v1, v2, color = y)) + geom_point()

table(dfc$y)
table(z1) / 500
table(sup)[2:3] / (sum(table(sup)[2:3]))

tuneGrid <- expand.grid(mtry = 2)
pd = data.frame(mat.or.vec(20, 3))
colnames(pd) = 0:2
gd = pd
k = 1
mm = list()

ptimes = vector(length = 20)
qtimes = vector(length = 20)

for(i in 1:20){
  
  s = Sys.time()
  xl = local_perm_imp_cm(formula = y ~ ., data = dfc, 
                       method = "rf", tuneGrid = tuneGrid, 
                       nsim = i*10, folds = 5)
  ptimes[i] = Sys.time() - s

  s1 = Sys.time()
  xg = local_grid_imp_cm(formula = y ~ ., data = dfc, 
                         method = "rf", tuneGrid = tuneGrid, 
                         nsim = i*10, folds = 5, quantile_grid = T)
  qtimes[i] = Sys.time() - s1
  
  # d1 = data.frame(values = dfc[, 1], perm = xl$local_imp$v1, 
  #                 grid = xg$local_imp$v1)
  # print(ggpairs(d1, c(1, 3), mapping = aes(color = sup)))
  
  l = data.frame(perm = xl$local_imp$v1, grid = xg$local_imp$v1)
  l$group = sup
  
  l$m = i*10
  mm[[k]] = l
  
  j = data.frame(l %>% group_by(group) %>% 
                   summarise(p_mid = round(median(perm), 4),
                             g_mid = round(median(grid), 4),
                             p_spread = round(mad(perm), 4),
                             g_spread = round(mad(grid), 4)))
  print(j)
  pd[k, ] = j$p_spread
  gd[k, ] = j$g_spread
  k = k + 1
}

# ptimes
# qtimes
# ggplot(mapping = aes(x = 1:20*10, y = ptimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 9), breaks = c(0, 3, 6, 9))
# ggplot(mapping = aes(x = 1:20*10, y = qtimes)) + geom_point() + 
#   geom_line() + scale_y_continuous(limits = c(0, 9), breaks = c(0, 3, 6, 9))

dat = data.frame(M = 1:20*10, ptimes, qtimes)
dat = dat %>% pivot_longer(cols = 2:3)

ggplot(dat, aes(x = M, y = value, colour = name, group = name)) + 
  geom_point() + 
  geom_line() +
  scale_y_continuous(limits = c(0, 20), breaks = c(0, 5, 10, 15, 20))

dq = dat |> filter(name == "qtimes")
lm(value ~ M, dq)

# pd$nsim = 1:20*10
# pdl = pivot_longer(pd, 1:3, names_to = "group", values_to = "value")
# gd$nsim = 1:20*10
# gdl = pivot_longer(gd, 1:3, names_to = "group", values_to = "value")
# 
# bdl = pdl
# colnames(bdl)[3] = "perm"
# bdl$grid = gdl$value
# bd = pivot_longer(bdl, 3:4, names_to = "type", values_to = "value")
# 
# ggplot(bd, aes(x = nsim, y = value, col = group)) + 
#   geom_line() + geom_point() + facet_wrap(vars(type))
# 
# ggplot(bd, aes(x = nsim, y = value, col = type)) + 
#   geom_line() + geom_point() + facet_wrap(vars(group))



mmm = rbind(mm[[1]], mm[[2]], mm[[3]], mm[[4]], mm[[5]],
      mm[[6]], mm[[7]], mm[[8]], mm[[9]], mm[[10]],
      mm[[11]], mm[[12]], mm[[13]], mm[[14]], mm[[15]],
      mm[[16]], mm[[17]], mm[[18]], mm[[19]], mm[[20]])

ggb = ggplot(mmm, aes(x = m, y = grid, col = group)) + 
  geom_point(position = position_jitter(width = 0.2)) +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:5*40, limits = c(0, 201)) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

# m1 = mmm %>% filter(m == 1)
# 
# ggplot(m1, aes(x = perm, y = grid, colour = group)) + 
#   geom_point() +
#   geom_hline(yintercept = c(0, .349, .651))

# hline <- data.frame(
#   group = factor(0:2),  # Match the facet variable
#   y = c(0, .349, .651)  # Different hline values for each facet
# )

# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group), ncol = 1)
# 
# ggplot(mmm, aes(x = m, y = grid, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(data = hline, aes(yintercept = y)) + 
#   scale_x_continuous(breaks = 1:20*5) + 
#   facet_wrap(vars(group))



gpb = ggplot(mmm, aes(x = m, y = perm, col = group)) + 
  geom_point(position = position_jitter(width = 0.07)) +
  geom_hline(yintercept = c(0, .349, .651)) + 
  scale_x_continuous(breaks = 0:5*40, limits = c(0, 201)) +
  scale_y_continuous(limits = c(-0.2, 1.05), breaks = -1:5 / 5)

ggb + gpb + plot_layout(guides = "collect", axes = "collect")

# ggplot(mmm, aes(x = m, y = perm, col = group)) + 
#   geom_point(position = position_jitter(width = 0.2)) +
#   geom_hline(yintercept = c(0, 1/3, 2/3)) + 
#   scale_x_continuous(breaks = 1:20) + facet_wrap(vars(group))
```




# Molnar Imp


```{r}
n <- 1000 # increase higher 1000
set.seed(444) # 123
x1 = rnorm(n, 0, 1)
x2 = rnorm(n, 0, 1)
x3 = rbinom(n, 1, 0.5)
e = rnorm(n, 0, 0.5)

y = x1 + x2 + 10*ifelse(x3 == 0, x1, x2) + e

dfx = as.data.frame(cbind(x1, x2, x3, y))

# Create a regression task
task1 = mlr::makeRegrTask(data = dfx, target = "y")
learner <- makeLearner("regr.randomForest")
model <- train(learner, task1)

# Compute feature importance
ici <- featureImportance(model, data = dfx, target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

# View results
print(ici)
ici$importance

# Plot results
pi.curve = plotImportance(ici, feat = "x1", mid = "mse", 
                          individual = FALSE, hline = TRUE)
ici.curves = plotImportance(ici, feat = "x1", mid = "mse", 
                            individual = TRUE, hline = FALSE)

# 
# pi.curve$data = pi.curve$data |> arrange(replace.id)
# ici.curves$data = ici.curves$data |> arrange(replace.id)

pi.curve + aes(color = factor(x3))
ici.curves + aes(color = factor(x3))

pi.curve + ici.curves + plot_layout(axes = "collect")


iii = ici$importance |> 
  pivot_wider(id_cols = c(row.id, n.feat.perm), names_from = features, 
              values_from = mse) |>
  group_by(row.id) |>
  summarize(x1 = mean(x1), x2 = mean(x2), x3 = mean(x3)) |>
  dplyr::select(!row.id)
iii

ggplot(dfx, aes(x = x1, y = iii$x1)) +
  geom_point()
ggplot(dfx, aes(x = x1, y = iii$x1, color = factor(x3))) +
  geom_point()
ggplot(dfx, aes(x = x1, y = iii$x1, color = factor(x3))) +
  geom_point() + ylim(-5, 50)


iii = ici$importance |> 
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mse) |>
  group_by(replace.id) |>
  summarize(x1 = mean(x1), x2 = mean(x2), x3 = mean(x3)) |>
  dplyr::select(!replace.id)
iii

ggplot(dfx, aes(x = x1, y = iii$x1, color = factor(x3))) +
  geom_point()


rr = row.names(dfx[x3 == 0, ]) |> as.numeric()
nrr = row.names(dfx[x3 == 1, ]) |> as.numeric()

# Compute feature importances for pre-known groups
ic1 <- featureImportance(model, data = dfx[x3 == 0, ], target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

pi.curve1 = plotImportance(ic1, feat = "x1", mid = "mse", 
                          individual = FALSE, hline = F)

i1 = ic1$importance |>
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mse) |>
  group_by(replace.id) |>
  summarize(x1 = mean(x1), x2 = mean(x2), x3 = mean(x3)) # |>
  # dplyr::select(!replace.id)
i1$replace.id = rr

ic2 <- featureImportance(model, data = dfx[x3 == 1, ], target = "y", 
                         n.feat.perm = 25,
                         local = TRUE)

pi.curve2 = plotImportance(ic2, feat = "x1", mid = "mse", 
                          individual = FALSE, hline = F)

i2 = ic2$importance |> 
  pivot_wider(id_cols = c(replace.id, n.feat.perm), names_from = features, 
              values_from = mse) |>
  group_by(replace.id) |>
  summarize(x1 = mean(x1), x2 = mean(x2), x3 = mean(x3)) #|>
  # dplyr::select(!replace.id)

i2$replace.id = nrr

ii = as.data.frame(rbind(i1, i2)) |> arrange(replace.id)

ggplot(dfx, aes(x = x1, y = ii$x1, color = factor(x3))) +
  geom_point()


pi.curve1 + ylim(-10, 460) + pi.curve2 + plot_layout(axes = "collect")
```
